# Generated by Django 2.1 on 2020-03-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=200)),
                ('borrower_trade_years', models.FloatField(default=0.0)),
                ('borrower_turnover_yearly', models.FloatField(default=0.0)),
                ('borrower_machine_vehicle_purchase', models.BooleanField(default=False)),
                ('borrower_purchases_with_min_outstanding_in_thousands', models.FloatField(default=0.0)),
                ('debit_credit_card_payment_txn', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
