# Generated by Django 2.1 on 2020-03-13 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LenderPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_years', models.FloatField(default=0.0)),
                ('turnover_per_year_in_thousands', models.FloatField(default=0.0)),
                ('machine_vehicle_purchase', models.BooleanField(default=False)),
                ('purchases_with_min_outstanding_in_thousands', models.FloatField(default=0.0)),
                ('debit_credit_card_payment_txn', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LenderTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lenders',
            name='lender_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.LenderTypes'),
        ),
        migrations.AddField(
            model_name='lenderpreferences',
            name='lender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.Lenders'),
        ),
        migrations.AddField(
            model_name='lenderpreferences',
            name='lender_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.LenderTypes'),
        ),
    ]
